# Generated by Django 4.1.3 on 2022-11-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approved",
            options={"ordering": ["unit"]},
        ),
        migrations.AlterModelOptions(
            name="registeredstudents",
            options={"ordering": ["unit"]},
        ),
    ]
