# Generated by Django 4.1.3 on 2022-11-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contact",
            field=models.BigIntegerField(default=0, verbose_name="phone number"),
        ),
    ]
