# Generated by Django 4.1.3 on 2022-11-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_approved_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approved",
            name="total",
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
