# Generated by Django 4.1.3 on 2022-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_approved_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approved",
            name="total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
