# Generated by Django 4.1.3 on 2022-11-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_approved_total"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approved",
            options={"ordering": ["unit", "student", "present", "total"]},
        ),
    ]
