# Generated by Django 4.1.3 on 2022-11-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_approved_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approved",
            name="present",
            field=models.BooleanField(default=True),
        ),
    ]
