# Generated by Django 4.1.3 on 2022-11-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_approved_present"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approved",
            options={"ordering": ["unit", "created_at"]},
        ),
    ]
