# Generated by Django 4.1.3 on 2022-11-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_approved_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approved",
            options={"ordering": ["unit", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="approved",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="registeredstudents",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="units",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
