# Generated by Django 4.1.3 on 2022-11-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_approved_options_alter_approved_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approved",
            options={"ordering": ["-created_at", "unit"]},
        ),
    ]
