# Generated by Django 4.1.3 on 2022-11-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_registeredstudents_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registerunits",
            options={"ordering": ["created_at", "unit"]},
        ),
    ]
