# Generated by Django 4.1.3 on 2022-11-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_registerunits_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerunits",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.lecturerunit"
            ),
        ),
    ]
