# Generated by Django 4.1.3 on 2022-11-28 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_registerunits_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="units",
            options={"ordering": ["created_at", "code"]},
        ),
        migrations.AddField(
            model_name="units",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registerunits",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.units"
            ),
        ),
        migrations.DeleteModel(
            name="LecturerUnit",
        ),
    ]
