# Generated by Django 4.1.3 on 2022-11-28 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_units_options_units_lecturer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkStudents",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.registeredstudents",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.units"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "student", "status"],
            },
        ),
        migrations.DeleteModel(
            name="Approved",
        ),
    ]
