# Generated by Django 4.1.3 on 2022-11-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_markstudents_marked_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="markstudents",
            options={"ordering": ["date", "student", "status"]},
        ),
        migrations.RemoveField(
            model_name="markstudents",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="markstudents",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="markstudents",
            name="date",
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
