# Generated by Django 4.1.3 on 2022-12-01 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("start", models.CharField(max_length=400)),
                ("end", models.CharField(max_length=400)),
            ],
            options={
                "ordering": ["start", "end"],
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("status", models.BooleanField(default=False)),
                ("departure", models.TimeField()),
                ("arrival", models.TimeField()),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("description", models.CharField(max_length=400)),
                ("price", models.FloatField(default=0)),
                ("featured", models.BooleanField(default=False)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flights.route"
                    ),
                ),
            ],
            options={
                "ordering": [
                    "name",
                    "route",
                    "capacity",
                    "description",
                    "featured",
                    "departure",
                    "arrival",
                    "price",
                ],
            },
        ),
    ]
